# Generated by Django 4.1.7 on 2024-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
