# Generated by Django 4.1.7 on 2024-02-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_lead_date_remove_lead_lead_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
