# Generated by Django 4.1.7 on 2024-02-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
