# Generated by Django 4.1.7 on 2024-02-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
