# Generated by Django 4.1.7 on 2024-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_lead_additional_notes_lead_business_verticals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='additional_notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business_verticals',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_headquarters',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='divisional_operations',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='running_promotions',
            field=models.CharField(max_length=255),
        ),
    ]
