# Generated by Django 4.1.7 on 2024-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_remove_lead_date_remove_lead_lead_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_verticals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
