# Generated by Django 4.1.7 on 2024-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_lead_business_verticals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='divisional_operations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
