# Generated by Django 4.1.7 on 2024-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_alter_lead_business_verticals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_verticals',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='divisional_operations',
            field=models.CharField(max_length=255),
        ),
    ]
