# Generated by Django 4.1.7 on 2024-02-27 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_alter_lead_business_verticals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 2, 27, 13, 55, 7, 548452, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
