# Generated by Django 4.1.7 on 2024-02-28 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_lead_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(default=datetime.datetime(2024, 2, 28, 5, 12, 55, 599432, tzinfo=datetime.timezone.utc), max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
