# Generated by Django 4.1.7 on 2024-02-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_lead_lead_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_no',
        ),
    ]
