# Generated by Django 4.1.7 on 2024-02-28 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_remove_lead_lead_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(default=datetime.datetime(2024, 2, 28, 8, 31, 35, 976339, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
    ]
