# Generated by Django 4.1.7 on 2024-02-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_alter_lead_lead_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
