# Generated by Django 4.1.7 on 2024-02-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
