# Generated by Django 4.1.7 on 2024-02-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(default='chh', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.CharField(default='lll', max_length=255),
        ),
    ]
