# Generated by Django 4.1.7 on 2024-02-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_alter_lead_contact_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
