# Generated by Django 4.1.7 on 2024-02-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
